name: build and test
on:
  pull_request:
    branches: [master]
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
jobs:
  build:
    name: "Build and Test on os: ${{ matrix.os }}. dotnet SDK version: ${{ matrix.dotnet }}"
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        dotnet: ['5.0.x']
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup ${{ matrix.dotnet }} .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: dotnet restore 
        run: dotnet restore

      - name: dotnet tool restore
        run: dotnet tool restore

      - name: Build with dotnet
        run: |
          dotnet build --configuration Debug NLoop.Server

      - name: Run property test in ${{ matrix.os }}
        run: dotnet test tests/NLoop.Server.Tests -- RunConfiguration.TestSessionTimeout=30000

      - name: Prepare docker images for integration tests.
        run: cd tests/NLoop.Server.Tests && source env.sh && docker-compose build

      - name: Run integration tests in ${{ matrix.os }}
        run: dotnet test tests/NLoop.Server.Tests -- RunConfiguration.TestSessionTimeout=30000

