name: release
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
on:
  push:
    branches:
      - "add_openapi_html"

jobs:
  deploy_openapi_html:
    name: "push openapi.html to gh-pages"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "prepare node"
        uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: "build openapi.yml"
        run:
          npx redoc-cli bundle openapi.yml -o docs/openapi.html && touch docs/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: docs
