name: publish(master)
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
on:
  push:
    branches:
      - master
      - 'nightly*' # to workaround regular publishing process

jobs:
  pack_and_push:
    name: "publish "
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
        dotnet: ['5.0.202']
        include:
          - os: ubuntu-18.04
            RID: linux-x64
          - os: windows-latest
            RID: win-x64
          - os: macos-latest
            RID: osx-x64
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup 3.1.200 .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200

      - name: publish (server)
        run: |
          bash -c "dotnet publish -c Release --self-contained true -r ${{ matrix.RID }} NLoop.Server --version-suffix date$(date +%Y%m%d-%H%M).git-$(git rev-parse --short=7 HEAD)-${{ matrix.RID }}"
      - name: publish (cli)
        run: |
          bash -c "dotnet publish -c Release --self-contained true -r ${{ matrix.RID }} NLoop.CLI --version-suffix date$(date +%Y%m%d-%H%M).git-$(git rev-parse --short=7 HEAD)-${{ matrix.RID }}"
